### ISSUE TITLE
Detail the method of testing primality

### ISSUE THREAD

**Issue by dsernst** [lborgav/is-prime#1]
It would be handy if the readme showed how primality was computed.

I tried looking at `index.js`, but it wasn't clear to me what these lines — https://github.com/lborgav/is-prime/blob/master/index.js#L19-L21 — were trying to do, or how long they'd take to run.

Thanks! :smile:

**Comment by lborgav** [comment]
Sorry for not pointing this out in Readme. I'll improve it

This is a number theory property that all primes have (6k + 1) or (6k - 1)-form. This way can speed up the primality test:

From [Wikipedia](https://en.wikipedia.org/wiki/Primality_test):

"The algorithm can be improved further by observing that all primes are of the form 6k ± 1, with the exception of 2 and 3. This is because all integers can be expressed as (6k + i) for some integer k and for i = −1, 0, 1, 2, 3, or 4; 2 divides (6k + 0), (6k + 2), (6k + 4); and 3 divides (6k + 3). So a more efficient method is to test if n is divisible by 2 or 3, then to check through all the numbers of form 6k ± 1 <= sqrt(n). This is 3 times as fast as testing all m."

**Comment by dsernst** [comment]
Interesting! Thanks for the link.

**Update:** Just saw this following paragraph:

> As c → ∞, the number of values that c#k + i can take over a certain range decreases, and so the time to test n decreases. For this method, it is also necessary to check for divisibility by all primes that are less than c. Observations analogous to the preceding can be applied recursively, giving the Sieve of Eratosthenes.

If you're interested, I wrote that function, which also keeps the Sieve cached for quicker repeated tests: https://github.com/dsernst/quick-is-prime

**Comment by lborgav** [comment]
@dsernst 
I'll check this out! Thanks!
